"""group ondelete update

Revision ID: 05433de809a1
Revises: 9714c4788bd2
Create Date: 2026-04-22 12:41:20.372291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05433de809a1'
down_revision: Union[str, None] = '9714c4788bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_group_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_group_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_group_id_fkey', 'users', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_group_id_fkey', 'tasks', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
