"""align nullability

Revision ID: ab7b8db92db5
Revises: 7c3f9b2b6a11
Create Date: 2026-04-27 14:00:34.171956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab7b8db92db5'
down_revision: Union[str, None] = '7c3f9b2b6a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'status',
               existing_type=postgresql.ENUM('submitted', 'analyzing', 'on_review', 'passed', 'failed', name='submissionstatus'),
               nullable=False)
    op.alter_column('submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_cases', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_cases', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'status',
               existing_type=postgresql.ENUM('submitted', 'analyzing', 'on_review', 'passed', 'failed', name='submissionstatus'),
               nullable=True)
    # ### end Alembic commands ###
