"""group ondelete update

Revision ID: f570f1e8f3b2
Revises: 05433de809a1
Create Date: 2026-04-22 12:43:56.151549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f570f1e8f3b2'
down_revision: Union[str, None] = '05433de809a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_cases_task_id_fkey', 'test_cases', type_='foreignkey')
    op.create_foreign_key(None, 'test_cases', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.create_foreign_key('test_cases_task_id_fkey', 'test_cases', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
